# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  workflow_dispatch:
  release:
   types: [published]
  #pull_request:
  #  branches:
  #  - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
      
    - uses: Kir-Antipov/mc-publish@v3.2
      with:
          # You don't need this section if you don't want to publish
          # your assets to GitHub
          files-primary: target/*.jar
          # files-secondary: build/libs/*-@(dev|sources|javadoc).jar
          
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: plugin Jar
        path: target/ChaosChallange-1.0-SNAPSHOT.jar
        retention-days: 5
